#!/usr/bin/env bash
# Generate asfand-dashboard/server/.env from deployed AWS CloudFormation stacks.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/asfand-dashboard/server/.env"
DEPLOY_ENV="${DEPLOY_ENV:-dev}"
REGION="${AWS_DEFAULT_REGION:-${CDK_DEFAULT_REGION:-us-east-1}}"

if ! command -v aws >/dev/null 2>&1; then
  echo "ERROR: aws CLI required"
  exit 1
fi

if ! aws sts get-caller-identity >/dev/null 2>&1; then
  echo "ERROR: AWS credentials not configured"
  exit 1
fi

stack_output() {
  local stack="$1" key="$2"
  aws cloudformation describe-stacks \
    --region "$REGION" \
    --stack-name "$stack" \
    --query "Stacks[0].Outputs[?OutputKey=='${key}'].OutputValue | [0]" \
    --output text 2>/dev/null || echo ""
}

COMPUTE="EraCompute-${DEPLOY_ENV}"
DATA="EraData-${DEPLOY_ENV}"
HOSTING="EraHosting-${DEPLOY_ENV}"

HTTP_API="$(stack_output "$COMPUTE" HttpApiUrl)"
USER_POOL_ID="$(stack_output "$COMPUTE" UserPoolId)"
CLIENT_ID="$(stack_output "$COMPUTE" UserPoolClientId)"
STREAM="$(stack_output "$COMPUTE" IncidentStreamName)"
API_ALB="$(stack_output "$HOSTING" ApiLoadBalancerUrl)"
DASHBOARD_URL="$(stack_output "$HOSTING" DashboardCloudFrontUrl)"

RDS_HOST="$(aws rds describe-db-instances \
  --region "$REGION" \
  --query "DBInstances[?contains(DBInstanceIdentifier, 'era') || contains(DBInstanceIdentifier, 'Era')].Endpoint.Address | [0]" \
  --output text 2>/dev/null || echo "")"

EVIDENCE_BUCKET="$(aws s3api list-buckets --query "Buckets[?contains(Name, 'evidence') && contains(Name, '${DEPLOY_ENV}')].Name | [0]" --output text 2>/dev/null || echo "")"

JWT_SECRET="$(openssl rand -base64 48 | tr -d '/+=' | head -c 48)"

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/configure-aws-env.sh — $(date -Iseconds)
PORT=3001
NODE_ENV=development
AWS_REGION=${REGION}
DEPLOY_ENV=${DEPLOY_ENV}

# Auth — real Cognito (local API talks to AWS services)
SKIP_AUTH=false
COGNITO_USE_MOCK=false
COGNITO_USER_POOL_ID=${USER_POOL_ID}
COGNITO_CLIENT_ID=${CLIENT_ID}
JWT_SECRET=${JWT_SECRET}
AUTO_CONFIRM_SIGNUP=false

# RDS is in private VPC — leave DATABASE_URL commented for local dev (uses in-memory DB)
# Uncomment when API runs in VPC (ECS) or via bastion/VPN:
# DATABASE_URL=postgresql://era_admin:PASSWORD@${RDS_HOST}:5432/emergencydb
# RUN_MIGRATIONS=true

# AWS service endpoints
HTTP_API_URL=${HTTP_API}
API_ALB_URL=${API_ALB}
KINESIS_STREAM_NAME=${STREAM}
S3_EVIDENCE_BUCKET=${EVIDENCE_BUCKET}
DASHBOARD_URL=${DASHBOARD_URL}
EOF

echo "Wrote $ENV_FILE"
echo ""
echo "Cognito User Pool: $USER_POOL_ID"
echo "API Gateway health: ${HTTP_API}/health"
echo "ECS API (when deployed): ${API_ALB}/api/health"
echo "Dashboard CDN: $DASHBOARD_URL"
echo ""
echo "Next: ./scripts/bootstrap-aws-admin.sh  (create admin@era.dev)"
echo "Then: ./scripts/start-era-dev.sh"
